export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILUR: 'LOGIN_FAILUR',
    
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILUR: 'LOGOUT_FAILUR'
}


export const userConstants = {
        USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
        USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
        USER_REGISTER_FAILUR: 'USER_REGISTER_FAILUR'
}